maintainer        "DigiTar"
maintainer_email  "info@digitar.com"
license           "BSD"
description      "Installs/Configures OpenIndiana packaging."
long_description "Installs/Configures OpenIndiana packaging."
version          "0.5.0"
